### ISSUE TITLE
md-autocomplete default input value does not work

### ISSUE THREAD

**Issue by whatjakecodes** [vuematerial/vue-material#1059]
### Steps to reproduce
Launch code pen
In the `data()` function, notice I tried to initialize the default value:
`colorValue: 'this-default-value-should-show',`

### Which browser?
Chrome on Macos

### What is expected?
Default value should pre-populate the input value

### What is actually happening?
Default value does not show up in the input

### Reproduction Link
https://codepen.io/jakesinthepen/pen/OxmPgw

**Comment by waratah** [comment]
I tried this on my component.   When I entered an empty string.  It have my prompt in large text on the screen.   Once I initialised to 'test' the prompt was smaller text (ie as per when you click or you have a value) but 'test' . did not appear on the screen.   This bug is verified.   Will see if I can work it out.

**Comment by waratah** [comment]
I updated the autocomplete.vue logic as follows:

  mounted() {
      this.$nextTick(() => {
        this.value = this.query;   // <<< .  added this

This is slightly better in the sense that the prompt is full height in the input area and when you click it shows the value primed with my initial text.   I don't think this is a proper fix though.

**Comment by itstyro** [comment]
Any update on this? I am facing the same issue with AutoComplete

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
