### ISSUE TITLE
The menu close will call tooltips

### ISSUE THREAD

**Issue by lasthrun** [vuematerial/vue-material#1079]
### Which browser?
chrome, vue 2.3.4,  vue-material 0.7.4

### What is expected?
when menu is open, if you click outside to close the menu, it should not call the tooltips

### What is actually happening?
when menu close, it call the tooltips

### Reproduction Link
https://codepen.io/lasthrun/pen/eGKpaa

**Comment by VdustR** [comment]
It happens because closing menu trigger button focused, and button focused make tooltip active.

I tried removing the focus and blur listener in the tooltip component, but still got issues.

![peek 2017-10-26 10-28](https://user-images.githubusercontent.com/29639463/32032220-92a0d138-ba38-11e7-88bc-2f79a55cbe41.gif)

And I think removing the menuTrigger focus event in the menu close method is not a good idea.

It's too hard for me :disappointed:

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by SergioReis97** [comment]
Having the same problem in 0.7.5, have any of you actually found a fix? @VdustR @lasthrun
