### ISSUE TITLE
md-whiteframe will shrink content in md-layout

### ISSUE THREAD

**Issue by hanxue** [vuematerial/vue-material#1128]
### Steps to reproduce
1. Create large sized content, e.g. table
2. Encapsulate the content in md-whiteframe, and nest the `md-whiteframe` in `md-layout`

### Which browser?
vue: 2.3.4
vue-material: 0.7.4
Chrome: 64.0.3265.0

### What is expected?
Content of md-whiteframe should expand to the full width

### What is actually happening?
Content is shrunk down. See https://codepen.io/hanxue/pen/XzgbEo

Removing the whiteframe will allow the table to expand to its proper width again. 

This is from my app, without `md-whiteframe`

![image](https://user-images.githubusercontent.com/760008/32732884-d1f5c962-c8c8-11e7-8ced-e4dbe6e46503.png)

and this is with `md-whiteframe`

![image](https://user-images.githubusercontent.com/760008/32732971-106c466c-c8c9-11e7-86af-5c13ab69a1f3.png)

### Reproduction Link
https://codepen.io/hanxue/pen/XzgbEo

**Comment by waratah** [comment]
work around is to add a class with width: 100%.

**Comment by hanxue** [comment]
@waratah Thanks, I have already been doing that 😃

**Comment by zapping** [comment]
@hanxue Its not an issue with `md-whiteframe`. If you remove all the code and just put the `vuetable` in the `md-whiteframe` then it fills up the entire width. The issue seems to with the `md-layout`s that has been set. In fact you seem to have hit a maze of layouts that you have one extra closing `md-layout` in the end.

Currently you have set `md-row` for the main `md-layout`. That means the sections should be one beside the other. You have set the first section to occupy 70% and that leaves the `vuetable` with just 30% of the width. That seems to be the issue.

Just try changing `md-row` to `md-column` in the main `md-layout`. That will fix the table stretch issue. You seem to want the sections to be one below the other then you should be using `md-column`. I have forked your pen https://codepen.io/zapping/pen/XzgqXj and made the above changes. Hope this is the layout you are trying to get to.
