### ISSUE TITLE
md-snackbar not showing above drawer in documentation

### ISSUE THREAD

**Issue by lucasfernog** [vuematerial/vue-material#1134]
![screenshot from 2017-11-14 08-12-46](https://user-images.githubusercontent.com/20051258/32774863-cf781518-c914-11e7-9109-10433f1f29a2.png)

### Steps to reproduce

Access https://vuematerial.io/components/snackbar, choose Left position snackbar and open it.

### Which browser?

Firefox 56.0
Ubuntu 17.04

### What is expected?

Snackbar above everything, including drawer.

### What is actually happening?

Navigation drawer is covering the snackbar.

### Reproduction Link

https://vuematerial.io/components/snackbar

**Comment by marcosmoura** [comment]
@lucasfernog This is really strange. I just tested it on mac, with this exactly same version. I will try to boot in a Linux env to take a look at this. Can you test it again?

**Comment by lucasfernog** [comment]
Testing with latest Firefox and Arch Linux, I found the steps to reproduce the error:
1- Open the snackbar docs page.
2- Open a centered snackbar and wait for the auto dismiss.
3- Open a left-position snackbar. It will be shown below the drawer.

It could be a caching position problem, but it's weird because it didn't happen with Chromium. I can debug it with the source code tomorrow.

**Comment by Samuell1** [comment]
Looks like removing `z-index` from `main-nav` but it can add some new issues with overflowing.

**Comment by fadafez** [comment]
Hi,
I'm sorry but I'm out of time now and I cannot open a new issue for a problem similar to this one. 
The problem is that I have added an external date picker, as the included one unfortunately is lacking a feature that I need (datetime range).

I've included this picker inside a card content, but when the calendar shows, it appears behind the card content. I've tried to increase its z-index, and other various fixes, but I had not luck. 

The only solution that appears to be working, is to completely remove the z-index property attached to the md-card element which contains the datepicker input. 

The page is still at a inital stage, I don't exclude at 100% some markup problems, but I wanted to point this out just to don't forget. Maybe in future I will check in for updates, if the problem gets solved by let's say, fixing the page markup.

bye :-)
