### ISSUE TITLE
Full of issues (Feeling bad?)

### ISSUE THREAD

**Issue by ConsoleTVs** [vuematerial/vue-material#1245]
I've been reading your docs and found out a few things that keep me away from going forward on it:

![image](https://user-images.githubusercontent.com/6124435/33501961-a7b7aa84-d6de-11e7-8511-c933338ef4b1.png)

It does not change input visuals until OK is pressed, found out 2 min after testing it. Also, firefox does not block weekends.
![image](https://user-images.githubusercontent.com/6124435/33502104-1f5d859a-d6df-11e7-9427-9b4a4f69b997.png)

There are more things but theese seems to be a real havy bug.. is it?

**Comment by marcosmoura** [comment]
The MdApp have a small problem related to flexbox. This is already fixed and will be release along with other fixed.

The datepicker thing is not an issue. It should be only assing the value when clicking on "ok" button.
Firefox do not have disabled weekends because it will not show the MdDatepicker, but the **native one**. I will provide an option to disable the native datepicker.

**Comment by ConsoleTVs** [comment]
Seems fair, when will this fix be online?

**Comment by marcosmoura** [comment]
This weekend!

**Comment by ConsoleTVs** [comment]
Thanks a lot marcos!
