### ISSUE TITLE
Setting width in pixels for md-table-head is ignored

### ISSUE THREAD

**Issue by fizxmike** [vuematerial/vue-material#1311]
### Steps to reproduce

See reproduction link below

### Which browser?

Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)

### What is expected?

I expect the width of the table column to be the width I input in pixels.

### What is actually happening?

All columns of table are equally spaced, ignoring my width in pixels.

### Reproduction Link

https://codepen.io/anon/pen/jYbbVb

**Comment by fizxmike** [comment]
For now I will use percentage widths, since that works... but there are columns that need specific pixel widths. (also pixel widths worked in the previous version of vue-material).

**Comment by VdustR** [comment]
Check this [example](https://codepen.io/VdustR/pen/eypJJr).

Table width is `100%` as default in Vue Material. I set it `auto` to make it the same as **With HTML (expected)**.

Then you could set `min-width` to `.md-table-head-container` and `.md-table-cell-container` instead of `width` to `table`.

If you want it be more similar to **With HTML (expected)**, you could remove the padding:

```scss
.md-table .md-table-head-text,
.md-table .md-table-cell .md-table-cell-container {
  padding-right: 0;
  padding-left: 0;
}
```

If you want make code like this works with scoped css, you may need add `/deep/` with scss. Check **Deep Selectors** in [vue-loader - Scoped CSS](https://vue-loader.vuejs.org/en/features/scoped-css.html).
