### ISSUE TITLE
Select does not work with dialog.

### ISSUE THREAD

**Issue by koreus7** [vuematerial/vue-material#1316]
### Steps to reproduce

Using the latest (Beta 7) vue-material
1. Create an md-dialog
2. Put an md-select in the dialog

### Which browser?

Tested in electron.

### What is expected?

When the md-dialog is opened the md-select displays the options when clicked.

### What is actually happening?

Clicking on the select label does not open a selection popup.

When closing the dialog you can briefly see the selection popup.

### Reproduction Link

I tried to make a fiddle but I can't seem to get dialogs working in codepen. This could be another issue or it could just be because i'm new to this.

Here is my attempt:
[https://codepen.io/anon/pen/NXxVzz](https://codepen.io/anon/pen/NXxVzz)

I have the bug in my codebase but I would like to create a minimal example. Currently blocked because dialogs don't seem to work in codepen.

**Comment by zapping** [comment]
Your pen has been forked to https://codepen.io/zapping/pen/YYqzOv
The Vue-Material js you had set was not that of beta. 
You need to include the default css of Vue-Material. 
The when you call the Vue-Material plugin it should be `Vue.use(VueMaterial.default)`

Made the above changes and added a select in your Dialog. But the issue is the options of the select opens behind the Dialog. As a temporary fix or work-around you can set a z-index for the select option higher than the dialog in your css like this 

`.md-menu-content{z-index:11;}`

**Comment by Samuell1** [comment]
Duplicated of: https://github.com/vuematerial/vue-material/issues/1149
