### ISSUE TITLE
[MdTable] Md-Fixed-Header not responsive

### ISSUE THREAD

**Issue by SirNeural** [vuematerial/vue-material#1350]
### Steps to reproduce

Create an instance of MdTable with an attribute of md-fixed-header, the size is manually set in px and is not responsive to the size of viewport.

### Which browser?

Vue-Material@1.0.0-beta-7
Vue@^2.5.0
Electron@1.7.10

### What is expected?

MdTable should be responsive to the size of the viewport, and is, but once a md-fixed-header is tacked on, it no longer becomes responsive and cuts off at some hardcoded limit.

### What is actually happening?

I believe there is some hardcoded value in px that affects the size of the MdTable when the md-fixed-header attribute is provided.

### Reproduction Link

With md-fixed-header: https://codepen.io/anon/pen/RxKMxW https://i.imgur.com/b9KmNAv.png
Without md-fixed-header: https://codepen.io/anon/pen/gogeKL https://i.imgur.com/uKQYsjs.png

Sorry for creating so many bug reports about MdTable, I just encountered a lot of unexpected behavior when working with [MdTable] in my app today

**Comment by VdustR** [comment]
Since the header is fixed, you need to set height to the table.

https://codepen.io/VdustR/pen/QadxPK

We don't define `100vh` to inside the component because there might be other cases like spliting the screen 50%, 50% for different components. I think it's better to set the height you want case by case.

Don't feel sorry. Thanks for using Vue Material and report these bugs. That helps a lot.

**Comment by SirNeural** [comment]
Hi, sorry to bring this up again, but it seems the latest beta-8 version hard-codes height and max-height values, in the element style="" itself, overriding any of my settings. Is there any way to fix this?

**Comment by Samuell1** [comment]
There is issue for it #1497
