### ISSUE TITLE
[MdDatepicker] Dates are reversed in Safari

### ISSUE THREAD

**Issue by andershjort** [vuematerial/vue-material#1422]
### Steps to reproduce
Go to https://vuematerial.io/components/datepicker
using Safari

### Which browser?
Safari on Osx Version 11.0.2 (12604.4.7.1.6)

### What is expected?
Date format should be dd/mm/yyyy

### What is actually happening?
Date format is yyyy-mm-dd

**Comment by Samuell1** [comment]
This is maybe fixed in dev branch, @VdustR can you check it please?

**Comment by VdustR** [comment]
because safari do not support `<input type="date">`, it's show 'YYYY-MM-DD' as default while input type is `"text"`:

https://github.com/vuematerial/vue-material/blob/6a719b5c2421d2efadb3bc522693e438a5a01066/src/components/MdDatepicker/MdDatepicker.vue#L101

As the `dev` branch set `mdOverrideNative` `ture` as default, all date picker would be shown as `YYYY-MM-DD` as default because the input type is `text` while `mdOverrideNative` is `true`.

**Comment by andershjort** [comment]
There is a global property 
Vue.prototype.$material.locale.dateFormat
Maybe the formattedDate should default to that instead of hardcodet 'YYYY-MM-DD' ?

**Comment by Samuell1** [comment]
@andershjort yes, thats should be there. thanks for finding this!
