### ISSUE TITLE
[MdMenu] does not close in chrome/iOS

### ISSUE THREAD

**Issue by oeway** [vuematerial/vue-material#1503]
I used MdMenu in a website, it works with desktop chrome, but when I open it in a ios version of chrome, the menu does not close when I click outside or clicked one item. The same happened with Safari/iOS version. I can't reproduce it with the mobile emulator in chrome dev tools. Not sure what happened.

**Comment by Samuell1** [comment]
Can you reproduce it on https://www.browserstack.com ?

**Comment by wozturk** [comment]
I think this issue is unresolved:
To reproduce open https://vuematerial.io/components/menu/ on the iPhone simulator (tested on iOS 10) or on an iPhone 7 with iOS 10, click on any of the options to open a menu (eg the first option "bottom start"). Now click/touch anywhere outside of the menu that just popped up... the menu will not close
Happens on chrome, safari and firefox on iOS.
Btw the menus do close on Android devices

**Comment by csteeg** [comment]
@Samuell1 could you please re-open the issue? It's reproducable on the url @wozturk  mentioned on browserstack as well #os=iOS&os_version=9.0&device=iPhone+6S&device_browser=safari) 
The menus only close when opening other menus, there is no other way to close the menus on iOS

**Comment by Samuell1** [comment]
Maybe its solved here: #1588

**Comment by wozturk** [comment]
@Samuell1 I think #1588 is an issue about the links inside the menu. These seem to work fine when implemented correctly. This issue is about being able to dismiss the popup menu by clicking outside of the box, which isn't working on iOS

**Comment by Samuell1** [comment]
@wpots I missclicked and posted a id to issue not to a PR: this should solve any problems with clicking outside too #1630
