### ISSUE TITLE
[MdStepper] - Has zero height in IE11

### ISSUE THREAD

**Issue by BigBadaboom** [vuematerial/vue-material#1558]
In IE 11, `class=".md-stepper"` elements collapse to zero height

The "100%" value for flex-basis in this rule seems to be the culprit.

```
.md-stepper {
    width: 100%;
    -webkit-box-flex: 1;
    flex: 1 0 100%;
    padding: 16px 24px;
}
```

Changing this rule to the following seems to work fine, without any ill effects.

```
.md-stepper {
    width: 100%;
    -webkit-box-flex: 1;
    flex: 1;
    padding: 16px 24px;
}
```

**Comment by Samuell1** [comment]
It doesnt broke anything in other browsers?

**Comment by BigBadaboom** [comment]
Correction.  My suggested fix was not quite correct.

The `flex` property in this rule seems to be unnecessary.  I added the following rule to my CSS and it fixed IE11. It also seems to still work correctly in Firefox and Chrome. 

```
.md-stepper {
	flex: none;
	-webkit-box-flex: none; /* not sure if this is needed or not */
}
```

I have only tested those three browsers.

**Comment by Samuell1** [comment]
Can you please make PR for it?

**Comment by iruizeguilaz** [comment]
I have come accross a similar issue with IE11 and tables.

In chrome or firefox I can see the table properly, but in IE11  does not appear the lines of the content. After checking the styles of my table I found that the problem comes form flex: 1;

If I remove that style form IE11 developer toools  I can see the data:

.md-table .md-table-content {
   -webkit-box-flex:1;
     flex: 1;
     overflow-x: auto;
      transition: height .3s cubic-bezier(.4, 0, .2, 1);
}

I have used a md-table

**Comment by Samuell1** [comment]
@iruizeguilaz can you please make separate issue for table?
