### ISSUE TITLE
[MdSnackbar] Snackbar for top and right position

### ISSUE THREAD

**Issue by christchan** [vuematerial/vue-material#1778]
Hello there, 

## **Background of Request**
I faced several design/style glitches when I use materializecss together with vue-material library in one application, therefore I want to use 100% vue-material library and remove the materializecss related files.

## **Problem**
After removing all materializecss and rely 100% on vue-material library, I experienced that vue-material lack of some components such as `navbar`, which I can eventually substitute with `md-toolbar` and adjust a little bit to make it fixed.
However, I also found out that `toast` is not available in here, instead we have `md-snackbar`

As far as I searched in **previous version** of vue-material, it has flexible option for the snackbar's `md-position` such as top left, top right, top center and so on. But I cannot find it anymore in the latest version.

## **Request**
Don't you think it is better to make the position flexible, since in Desktop web app, the best position for snackbar should be in the top center. 

Thank you

**Comment by Samuell1** [comment]
Hello,
Yes old version used a flexible version of snackbars, but new is built exactly according to the Google Material Design specs. Thats why we dont support other placements because its not in a specs and snackbars should be on bottom of the screen.

If you really want you can customize it with your custom css and overwrite our css but its not recommended because it can overlay with other things.
