### ISSUE TITLE
Dead Repo?

### ISSUE THREAD

**Issue by DavidLambauer** [vuematerial/vue-material#1962]
I can't see any progress in this repo? Is it frozen? Do you need contributer? Whats the issue?

**Comment by jeremyhart** [comment]
This is the most complete Vue material framework out there, I hope its not dead.
I'm wanting to use it on a project but I'm hesitant because it seems unmaintained.
Such a cool project, I hope it does get updated.

**Comment by githrdw** [comment]
> This is the most complete Vue material framework out there, I hope its not dead.
> I'm wanting to use it on a project but I'm hesitant because it seems unmaintained.
> Such a cool project, I hope it does get updated.

Well, I think [Vuetify](https://github.com/vuetifyjs/vuetify) is the most complete Vue material framework.
Their last update was yesterday which was release No. 184 unlike vue-material it's 32th release half a year ago.

**Comment by mrwhy-orig** [comment]
@Samuell1 @VdustR @marcosmoura @Morgul  Any comments to this?

**Comment by DavidLambauer** [comment]
The fact that there is no comment means that this repo is dead.

**Comment by mrwhy-orig** [comment]
Certainly not. There a cases where people are just doing other stuff or are on vacation or... It is an open source project and sometimes the maintainers just need some time to coordinate themselves or to make some money elsewhere... I'm hoping there will be a comment, and may be you are right, but maybe not.

**Comment by Samuell1** [comment]
Well, I am still waiting for @marcosmoura to release a new version from dev branch then we can continue with developing and bugfixing, but i think he is now very busy in work.

**Comment by tzjoke** [comment]
You can see the info in their homepage:

> Disclaimer: This is a beta version. The API is not going to change, but be careful to use it in production.

**Comment by Tajnymag** [comment]
> 
> 
> > > This is the most complete Vue material framework out there, I hope its not dead.
> > > I'm wanting to use it on a project but I'm hesitant because it seems unmaintained.
> > > Such a cool project, I hope it does get updated.
> > 
> > 
> > Well, I think [Vuetify](https://github.com/vuetifyjs/vuetify) is the most complete Vue material framework.
> > Their last update was yesterday which was release No. 184 unlike vue-material it's 32th release half a year ago.
> 
> @mrwhy-orig, vuetify is a very good project and seems more active and with more components but its performance is much worse (at least testing its website) that vue-material. For example, if you run in chrome dev tools the performance tab tool, with datatable demo pages:
> 
>     * vuetify:  ( [vuetifyjs.com/en/components/data-tables](https://vuetifyjs.com/en/components/data-tables) ): scripting time + rendering is 8 about seconds!!!
> 
>     * vue-material: ( [vuematerial.io/components/table](https://vuematerial.io/components/table/) ): scripting time + redering is about 4 seconds (and in my projects is even more fast).
> 
> 
> My conclusion: vue material is more fast and responsive than vuetify. Vuetify for me is slow for the user experience that I need.
> 
> I hope this project continues to be maintained. I ask to @Samuell1 @VdustR @marcosmoura @Morgul : Even if you can not be active now, do you intend to continue maintaining it? Thanks very much.

You're right. In my testing, Vuetify's sidebar/drawer takes more than a full second to start it's animation on my mobile. VueMaterial's drawer open in an instant.

**Comment by jacekkarczmarczyk** [comment]
> vuetify: ( https://vuetifyjs.com/en/components/data-tables ): scripting time + rendering is 8 about seconds!!!
> vue-material: ( https://vuematerial.io/components/table/ ): scripting time + redering is about 4 seconds (and in my projects is even more fast).

Compare also the number of examples on both pages (vuetify - 17, vue-material - 9) as well as navigation drawer, toolbar, right panel and API table that are richer in vuetify than in vue-material. 

It would be interesting to compare both frameworks using similar sets of components (something like page with just tables, with equal number of tables and equal numbers of items in corresponding tables)

**Comment by Mr-Markus** [comment]
It seems that this repo is still dead... last commit or PR on code was about 2 month ago.

But why?

I have to switch to vuetify...  Pity!

**Comment by marcosmoura** [comment]
@Mr-Markus I'm sorry to see that you are migrating. I don't see any reason to flag something as dead because you don't see any **public** commits at the **master** branch. We've released the last beta version 2 months ago, but we are still working on it. Although 1.0-beta lacks some features if compared with other frameworks, it does not have critical bugs and the important ones that we already know are being solved by me and some other great people. The features that we don't have, can be easily integrated with Vue Material in the near future or can also be developed as a 3rd party component, for example. 
It's not a pity that Vue Material does not have a lot of commits daily if compared with other Vue UI frameworks.

**Comment by Mr-Markus** [comment]
I liked it to use the repo, but after using it a few month I found so many bugs and missing features without any solutions. So I can't use it in it's latest version as it is.
Issues and PRs from the past are mostly without any answer. Why? 

I also can not see any development in other branches, which i can't understand when you see you are working on it.

And there are only beta and no stable releases :-(

I thoght about forking it and create a PR for this repository (md-table footer), but there are open PRs from mid of 2018 and because of that i have no good feeling that my work will be integrated and another release will be published in the near future.
And by the way... master branch can not be build, thats a real pity, too

Maybe there will be more work in the future, but at the moment it is difficult or impossible to use it for production websites

**Comment by DavidLambauer** [comment]
We switched to vuetify which was an awesome decision. They put a lot of work into it which is not compareable to this one. Unfortunately we would have sticked with vue-material if there was more contribution, bug handling and better response times.
