### ISSUE TITLE
Is the project out of maintenance？

### ISSUE THREAD

**Issue by danclive** [vuematerial/vue-material#2124]
Is the project out of maintenance ?

**Comment by Mr-Markus** [comment]
I asked the same half a year ago. No relevant changes since that. Other people asked a year ago.

It is still a Beta and bugs are not fixed here. I use vuetify instead, because it has a better community, is stable and has a great documentation.

**Comment by danclive** [comment]
I also know about vuetify, but my existing projects already use vue-material and it's hard to switch over.

**Comment by marqbeniamin** [comment]
Hi guys! I’m Ben from Creative Tim. I think I have some good news. We saw that the repository isn’t updated since 1 year ago. Our products are using also this framework and we are ready to start maintenance of this repository. We spoke with Marcos and he gave us admin rights on the repository. We are thinking of a first step to close some PR’s and some issues, the second step is to have a stable version 1.0.0. We are looking for contributors at this moment, so everyone who wants to contribute is very welcome. We want also to build a core team with 3 contributors which will have deploy rights. Please tell us your opinions:D

I've created on the official discord channel a poll about who is interested to become a contributor. If you want to become one please connect to this discord channel https://discord.gg/d9DtkJ and on the #general channel is a poll created by me and give us a 👍

Regards,
Ben
