### ISSUE TITLE
[core] Custom component examples

### ISSUE THREAD

**Issue by ardoramor** [vuematerial/vue-material#523]
Great library with a lot of features. I'm still evaluating it on two projects. I do feel it is a bit restrictive but that may be due to me being new to it. For example, inability to tap into library's configured variables or dictate them yourself (but that is on the roadmap). Yet, things like dialog open/close from are superb!

Anyway, my question is if you would be able to provide a tutorial on how to develop a custom component or extend an existing one. For example, if I wanted to create a rating component that uses the default theme, how would I tap into the theme values passed in? Also, because (at least from the quick look of it) default theme is calculated but not exposed, I'd need to create a custom theme, set it as default for vue-material, and then also apply it to my component?

How about extending vue-material components? Let's say I want to create a custom card component or something of the sort. Would you recommend extending current `md-card`?

**Comment by Morgul** [comment]
At the moment, the story around this doesn't seem great, but I can tell you how I've done it.

Generally speaking, with any vue based UI library, the idea is to treat these things like legos. You use the lower-level components to build your higher level components. So you don't _'extend'_ the md-card component, rather you _'compose'_ multiple components. Style changes, etc are done as overrides in your custom component, not as changes to the `md-card` component.

Now, vue material currently doesn't give you access to the theme information in a way that's nice to work with. Because I'm not going to be changing themes in my application, I just use chrome's inspector to pull the generated css properties, and use those when I need to extend or override. That's currently a pain point with this project. But, it's still perfectly capable of doing what you want.

You mentioned a rating component? Well, I build something not unlike that for a digital RPG site I'm working on. It's made from `md-checkbox` components, an `md-button` and an `md-modal`. Here's a little demo:

![lucky_dice](https://cloud.githubusercontent.com/assets/770655/24464742/6f7aa1b6-1470-11e7-95ed-9d1b2d7c89f4.gif)

If you're interested in the code, it's here:

https://github.com/Morgul/rpgkeeper/blob/ccase-major-update/client/components/pool.vue

**Comment by ardoramor** [comment]
Nice, thanks @Morgul. I guess one difficulty with component styling is that, unlike navite DOM base styling, styles are applies on top and most likely will take priority over something like `class` that may later be applied. Cool work on RPGKeeper, I'll check it out for more examples.

**Comment by Morgul** [comment]
Actually, my experience had been that because classes on a compound object are more specific, overriding just works.

And, thanks. Just make sure to stick to that branch for vue-material, beta is Vue 1.X and bootstrap, and master is angular 1.X.

**Comment by pablohpsilva** [comment]
@ardoramor [this](https://medium.com/@pablohpsilva/building-a-mdautocomplete-for-vue-material-framework-769aa9d86ea2) might help you :)

I hope you like it.
