### ISSUE TITLE
How to theme selected row of md-table

### ISSUE THREAD

**Issue by delaneyj** [vuematerial/vue-material#659]
### Steps to reproduce
Create a md-table
### Which browser?
Vue2 2.2.6, Vue-Material 0.7.1

### What is expected?
When hovering over a table row, highlight on selection to match the theme.  Possibly a semi-transparent version of accent or primary color.

### What is actually happening?
No matter what theme its always a light blue.

### Reproduction Link
[CodePen example](http://codepen.io/anon/pen/PpVdjJ)

**Comment by pablohpsilva** [comment]
Hello @delaneyj 
Dude, first things first: Thank you for opening this issue. Your care for this project is awesome. We appreciate it.

The [Material Design Table Component](https://material.io/guidelines/components/data-tables.html#data-tables-specs) does not follow the app theming, unless we're talking about the checkbox toggle or the alternative header. Rows, highlights and columns are always white, grayish like we implemented.

This is not a bug and we'll not implement this feature, because:
> Vue Material is lightweight framework built exactly according to the Material Design specs.

Thank you for your time and for using this framework. :D
