### ISSUE TITLE
 [mdTooltips] iPhone problems with tooltips and empty input entry animation

### ISSUE THREAD

**Issue by jackolo** [vuematerial/vue-material#729]
This happens both in Safari and Chrome 58.0 on iOS 10.3.1 with vue-material 0.7.1. It works fine on Android.

1. When the md-button contains md-tooltip then then first click on the button shows the tooltip and second one triggers the click event. 

2. After clicking in the empty input the label animation happens and the entire page ends up magnified at least 10 times. This can be reproduced on your site for the inline field or textarea samples. (As a side note - similiar samples on getmdl.io work fine on iOS.)

**Comment by pablohpsilva** [comment]
Hello @jackolo ! How are you? :D 
This happens because, while using mobile devices, the "hover" property on CSS is triggered like a "tap". That's why your first tap shows the tooltip and the second one actually clicks the button.

I strongly agree that this is an issue. We'll look into that ASAP. Thank you :D

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
