### ISSUE TITLE
 [mdSelect] in a modal

### ISSUE THREAD

**Issue by Bolandish** [vuematerial/vue-material#738]
Hi! 

i'm trying to add a md-select in a modal. Every time i try, it appends the select-options to the body, and is behind the modal and it scrolls with the body. 

How can i get it to append to the modal instead of the body?

**Comment by zapping** [comment]
Please check the 'Open Dialog' button in this pen and see if this is what you are looking for

https://codepen.io/zapping/pen/bBPyOz

**Comment by Bolandish** [comment]
The problem also appears in the codepen example you mention :)

**Comment by Bolandish** [comment]
![gif](https://cloud.githubusercontent.com/assets/7235443/25939074/df23c906-3631-11e7-8acd-eb13b1b60b50.gif)

**Comment by Samuell1** [comment]
I think if you open modal there should by overflow: hidden on body?

**Comment by Bolandish** [comment]
Yeah, i think it will fix it :)

**Comment by Bolandish** [comment]
@Samuell1 I dont think it's the right solution , but it works.. 👍

**Comment by zapping** [comment]
Hmm.. quite strange, because I get mine with all scrollbars and only my select scrolls. The pen view has be resized so that there is scroll all around. Could it be my system? I am on windows and the grab is from chrome. I tried on firefox too and its the same. 

![selectscroll](https://cloud.githubusercontent.com/assets/4123026/25987781/09047c16-3713-11e7-89ae-835b6a441bad.gif)

@Samuell1 and @pablohpsilva do you guys get it similar to @Bolandish.

**Comment by pablohpsilva** [comment]
Hello @zapping :D
Yeap, you're right. While using windows (and AFAIK linux too) you can't scroll elements that are not on focus/active, like macOS does. The gif above shows the right behavior :)

@Bolandish gif is super weird! LOL
We'll check it out ASAP.

**Comment by Bolandish** [comment]
@pablohpsilva thank you 😄 
Let me know if you need something from me 😄

**Comment by Bolandish** [comment]
@pablohpsilva 

Maybe it also should close when clicking outside the dropdown? Just an idea 😄

**Comment by capttrousers** [comment]
This looks the same as #547

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
