### ISSUE TITLE
md-menu trigger transparent

### ISSUE THREAD

**Issue by doespresso** [vuematerial/vue-material#758]
Having many md-menu on page.
When one menu is opened and make click to another menu trigger is only closes the opened menu but not open clicked.
How to fix?

**Comment by VicarEscaped** [comment]
This behavior is by design. Click outside mdMenu handled by *md-backdrop*, which overlaps other components. To achive what you describe, vue-material need different handle for click outside element.

**Comment by pablohpsilva** [comment]
@doespresso 
Every time you open a mdMenu, it will created a faded backdrop that cover the whole page on top of everything else. 
Like @VicarEscaped said, this is by design. But, answering your question: You could listen to the event of @close from the mdMenu and, programmatically close all the menus.
