### ISSUE TITLE
 [mdTable] Option to align right the md-selection checkboxes. 

### ISSUE THREAD

**Issue by Hidejec** [vuematerial/vue-material#873]
Is there a way to align the checkbox to the right of the table? Can you please implement this option thanks.

**Comment by pablohpsilva** [comment]
Hello @Hidejec 
vue-material follows the strict material design rules. Can you provide something to support this enhancement from [material design](https://material.io)?

**Comment by HelloDeadline** [comment]
Hi @pablohpsilva 
I have similar case - I need to place checkboxes to the right. The reason is that first column will contain small images (avatars) and I want to balance visual weight. 
I think that it is great to follow strict guidelines, but it is also great to have and option to sometimes break rules :)

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
