### ISSUE TITLE
I do not want to include Material Icons from Google CDN.How can I solve this issue

### ISSUE THREAD

**Issue by bisht-richa** [vuematerial/vue-material#973]

**Comment by pablohpsilva** [comment]
Hello @bisht-richa :D 
Easy, you could use [SVG's](http://vuematerial.io/#/components/icon) or you can download the material icons font and use it on your project. Download [this CSS file](https://fonts.googleapis.com/icon?family=Material+Icons) and then download [this font](https://fonts.gstatic.com/s/materialicons/v28/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw.woff2). Put those two in the same folder and then change the `src` line in the CSS folder with the downloaded font path.

Why didn't we do it as a guide on the vue-material website? Because material design icons are always changing. That font link is always changing and being updated.

I hope that helps you.

**Comment by bisht-richa** [comment]
Thank you :) Is there any better way to handle this ?

**Comment by Samuell1** [comment]
https://github.com/vuematerial/vue-material/issues/701#issuecomment-296571870
